# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Omega <- function(gamma, sigma, zeta, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_Omega', PACKAGE = 'JMMICSpack', gamma, sigma, zeta, GH_w, GH_z)
}

compute_Delta <- function(sigma, eta, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_Delta', PACKAGE = 'JMMICSpack', sigma, eta, GH_w, GH_z)
}

compute_logLik_JMMICS <- function(gamma, sigma, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_logLik_JMMICS', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_score_JMMICS <- function(gamma, sigma, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_score_JMMICS_slopes <- function(gamma, sigma, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_cheese_JMMICS <- function(gamma, sigma, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_cheese_JMMICS_slopes <- function(gamma, sigma, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_EB_JMMICS <- function(gamma, sigma, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_EB_JMMICS', PACKAGE = 'JMMICSpack', gamma, sigma, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_logLik_JMMICS_NegBin <- function(gamma, sigma, tau, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_logLik_JMMICS_NegBin', PACKAGE = 'JMMICSpack', gamma, sigma, tau, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_score_JMMICS_NegBin <- function(gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS_NegBin', PACKAGE = 'JMMICSpack', gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_score_JMMICS_NegBin_slopes <- function(gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS_NegBin_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_cheese_JMMICS_NegBin <- function(gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS_NegBin', PACKAGE = 'JMMICSpack', gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_cheese_JMMICS_NegBin_slopes <- function(gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS_NegBin_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, tau, DG_tau, Omega, Delta, zeta, eta, rand_indic, Nk, Nk_actual, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta)
}

compute_EB_JMMICS_NegBin <- function(gamma, sigma, tau, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_EB_JMMICS_NegBin', PACKAGE = 'JMMICSpack', gamma, sigma, tau, Omega, Delta, Nk, Nk_actual, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_logLik_JMMICS_ZIP <- function(gamma, sigma, Xi, Omega, Delta, Nk, Nk_actual, Nk0, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_logLik_JMMICS_ZIP', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, Nk, Nk_actual, Nk0, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_score_JMMICS_ZIP <- function(gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS_ZIP', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta)
}

compute_score_JMMICS_ZIP_slopes <- function(gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, rand_indic, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_score_JMMICS_ZIP_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, rand_indic, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta)
}

compute_cheese_JMMICS_ZIP <- function(gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS_ZIP', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta)
}

compute_cheese_JMMICS_ZIP_slopes <- function(gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, rand_indic, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta) {
    .Call('_JMMICSpack_compute_cheese_JMMICS_ZIP_slopes', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, theta, zeta, eta, rand_indic, Nk, Nk_actual, Nk0, Z0k, Zk, Yki, Xki, IDk, Wki, minNk, condSize, condOut, GH_w, GH_z, len_epsilon, len_alpha, len_beta)
}

compute_EB_JMMICS_ZIP <- function(gamma, sigma, Xi, Omega, Delta, Nk, Nk_actual, Nk0, Yki, IDk, Wki, minNk, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_EB_JMMICS_ZIP', PACKAGE = 'JMMICSpack', gamma, sigma, Xi, Omega, Delta, Nk, Nk_actual, Nk0, Yki, IDk, Wki, minNk, GH_w, GH_z)
}

compute_logLik_GLMM <- function(sigma, Delta, Nk_actual, Yki, IDk, Wki, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_logLik_GLMM', PACKAGE = 'JMMICSpack', sigma, Delta, Nk_actual, Yki, IDk, Wki, GH_w, GH_z)
}

compute_score_GLMM <- function(sigma, Delta, eta, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta) {
    .Call('_JMMICSpack_compute_score_GLMM', PACKAGE = 'JMMICSpack', sigma, Delta, eta, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta)
}

compute_score_GLMM_slopes <- function(sigma, Delta, eta, rand_indic, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta) {
    .Call('_JMMICSpack_compute_score_GLMM_slopes', PACKAGE = 'JMMICSpack', sigma, Delta, eta, rand_indic, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta)
}

compute_cheese_GLMM <- function(sigma, Delta, eta, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta) {
    .Call('_JMMICSpack_compute_cheese_GLMM', PACKAGE = 'JMMICSpack', sigma, Delta, eta, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta)
}

compute_cheese_GLMM_slopes <- function(sigma, Delta, eta, rand_indic, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta) {
    .Call('_JMMICSpack_compute_cheese_GLMM_slopes', PACKAGE = 'JMMICSpack', sigma, Delta, eta, rand_indic, Nk_actual, Yki, Xki, IDk, Wki, condOut, GH_w, GH_z, len_beta)
}

compute_EB_GLMM <- function(sigma, Delta, Nk_actual, Yki, IDk, Wki, GH_w, GH_z) {
    .Call('_JMMICSpack_compute_EB_GLMM', PACKAGE = 'JMMICSpack', sigma, Delta, Nk_actual, Yki, IDk, Wki, GH_w, GH_z)
}

