// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_Omega
NumericVector compute_Omega(NumericVector gamma, NumericVector sigma, NumericVector zeta, NumericVector GH_w, NumericVector GH_z);
RcppExport SEXP _MISclassICSpack_compute_Omega(SEXP gammaSEXP, SEXP sigmaSEXP, SEXP zetaSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Omega(gamma, sigma, zeta, GH_w, GH_z));
    return rcpp_result_gen;
END_RCPP
}
// compute_Delta
NumericVector compute_Delta(NumericVector sigma, NumericVector eta, NumericVector GH_w, NumericVector GH_z);
RcppExport SEXP _MISclassICSpack_compute_Delta(SEXP sigmaSEXP, SEXP etaSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Delta(sigma, eta, GH_w, GH_z));
    return rcpp_result_gen;
END_RCPP
}
// compute_logLik_MISclassICS
double compute_logLik_MISclassICS(NumericVector gamma, NumericVector gamma0, NumericVector gamma1, NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Omega, NumericVector Omega0, NumericVector Omega1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector Nk, NumericVector Nk_actual, NumericVector Yki, NumericVector Wk, NumericVector Xk, NumericVector IDk, LogicalVector VALIDk, int minNk, NumericVector GH_w, NumericVector GH_z);
RcppExport SEXP _MISclassICSpack_compute_logLik_MISclassICS(SEXP gammaSEXP, SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP OmegaSEXP, SEXP Omega0SEXP, SEXP Omega1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP NkSEXP, SEXP Nk_actualSEXP, SEXP YkiSEXP, SEXP WkSEXP, SEXP XkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP minNkSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega0(Omega0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega1(Omega1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk(NkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< int >::type minNk(minNkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_logLik_MISclassICS(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, minNk, GH_w, GH_z));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_MISclassICS
NumericVector compute_score_MISclassICS(NumericVector gamma, NumericVector gamma0, NumericVector gamma1, NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Omega, NumericVector Omega0, NumericVector Omega1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector zeta, NumericVector zeta0, NumericVector zeta1, NumericVector eta, NumericVector eta0, NumericVector eta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector Nk, NumericVector Nk_actual, NumericMatrix Zk, NumericMatrix Zk0, NumericMatrix Zk1, NumericVector Yki, NumericMatrix Xki, NumericMatrix Xki0, NumericMatrix Xki1, NumericVector Wk, NumericMatrix Zwk, NumericMatrix Zwk0, NumericMatrix Zwk1, NumericVector Xk, NumericMatrix Zxk, NumericVector IDk, LogicalVector VALIDk, int minNk, bool condSize, bool condOut, NumericVector GH_w, NumericVector GH_z, int len_alpha, int len_beta, int len_epsW, int len_epsX);
RcppExport SEXP _MISclassICSpack_compute_score_MISclassICS(SEXP gammaSEXP, SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP OmegaSEXP, SEXP Omega0SEXP, SEXP Omega1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP zetaSEXP, SEXP zeta0SEXP, SEXP zeta1SEXP, SEXP etaSEXP, SEXP eta0SEXP, SEXP eta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP NkSEXP, SEXP Nk_actualSEXP, SEXP ZkSEXP, SEXP Zk0SEXP, SEXP Zk1SEXP, SEXP YkiSEXP, SEXP XkiSEXP, SEXP Xki0SEXP, SEXP Xki1SEXP, SEXP WkSEXP, SEXP ZwkSEXP, SEXP Zwk0SEXP, SEXP Zwk1SEXP, SEXP XkSEXP, SEXP ZxkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP minNkSEXP, SEXP condSizeSEXP, SEXP condOutSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP, SEXP len_alphaSEXP, SEXP len_betaSEXP, SEXP len_epsWSEXP, SEXP len_epsXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega0(Omega0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega1(Omega1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta0(zeta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta1(zeta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk(NkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk(ZkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk0(Zk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk1(Zk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki(XkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki0(Xki0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki1(Xki1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk(ZwkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk0(Zwk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk1(Zwk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zxk(ZxkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< int >::type minNk(minNkSEXP);
    Rcpp::traits::input_parameter< bool >::type condSize(condSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type condOut(condOutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    Rcpp::traits::input_parameter< int >::type len_alpha(len_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type len_beta(len_betaSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsW(len_epsWSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsX(len_epsXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_MISclassICS(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_MISclassICS_slopes
NumericVector compute_score_MISclassICS_slopes(NumericVector gamma, NumericVector gamma0, NumericVector gamma1, NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Omega, NumericVector Omega0, NumericVector Omega1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector zeta, NumericVector zeta0, NumericVector zeta1, NumericVector eta, NumericVector eta0, NumericVector eta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector rand_indic, NumericVector Nk, NumericVector Nk_actual, NumericMatrix Zk, NumericMatrix Zk0, NumericMatrix Zk1, NumericVector Yki, NumericMatrix Xki, NumericMatrix Xki0, NumericMatrix Xki1, NumericVector Wk, NumericMatrix Zwk, NumericMatrix Zwk0, NumericMatrix Zwk1, NumericVector Xk, NumericMatrix Zxk, NumericVector IDk, LogicalVector VALIDk, int minNk, bool condSize, bool condOut, NumericVector GH_w, NumericVector GH_z, int len_alpha, int len_beta, int len_epsW, int len_epsX);
RcppExport SEXP _MISclassICSpack_compute_score_MISclassICS_slopes(SEXP gammaSEXP, SEXP gamma0SEXP, SEXP gamma1SEXP, SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP OmegaSEXP, SEXP Omega0SEXP, SEXP Omega1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP zetaSEXP, SEXP zeta0SEXP, SEXP zeta1SEXP, SEXP etaSEXP, SEXP eta0SEXP, SEXP eta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP rand_indicSEXP, SEXP NkSEXP, SEXP Nk_actualSEXP, SEXP ZkSEXP, SEXP Zk0SEXP, SEXP Zk1SEXP, SEXP YkiSEXP, SEXP XkiSEXP, SEXP Xki0SEXP, SEXP Xki1SEXP, SEXP WkSEXP, SEXP ZwkSEXP, SEXP Zwk0SEXP, SEXP Zwk1SEXP, SEXP XkSEXP, SEXP ZxkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP minNkSEXP, SEXP condSizeSEXP, SEXP condOutSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP, SEXP len_alphaSEXP, SEXP len_betaSEXP, SEXP len_epsWSEXP, SEXP len_epsXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma1(gamma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega0(Omega0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Omega1(Omega1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta0(zeta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta1(zeta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rand_indic(rand_indicSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk(NkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk(ZkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk0(Zk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zk1(Zk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki(XkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki0(Xki0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki1(Xki1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk(ZwkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk0(Zwk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk1(Zwk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zxk(ZxkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< int >::type minNk(minNkSEXP);
    Rcpp::traits::input_parameter< bool >::type condSize(condSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type condOut(condOutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    Rcpp::traits::input_parameter< int >::type len_alpha(len_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type len_beta(len_betaSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsW(len_epsWSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsX(len_epsXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_MISclassICS_slopes(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX));
    return rcpp_result_gen;
END_RCPP
}
// compute_logLik_MISclassGLMM
double compute_logLik_MISclassGLMM(NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector Nk_actual, NumericVector Yki, NumericVector Wk, NumericVector Xk, NumericVector IDk, LogicalVector VALIDk, NumericVector GH_w, NumericVector GH_z);
RcppExport SEXP _MISclassICSpack_compute_logLik_MISclassGLMM(SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP Nk_actualSEXP, SEXP YkiSEXP, SEXP WkSEXP, SEXP XkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_logLik_MISclassGLMM(sigma, sigma0, sigma1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, GH_w, GH_z));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_MISclassGLMM
NumericVector compute_score_MISclassGLMM(NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector eta, NumericVector eta0, NumericVector eta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector Nk_actual, NumericVector Yki, NumericMatrix Xki, NumericMatrix Xki0, NumericMatrix Xki1, NumericVector Wk, NumericMatrix Zwk, NumericMatrix Zwk0, NumericMatrix Zwk1, NumericVector Xk, NumericMatrix Zxk, NumericVector IDk, LogicalVector VALIDk, bool condOut, NumericVector GH_w, NumericVector GH_z, int len_beta, int len_epsW, int len_epsX);
RcppExport SEXP _MISclassICSpack_compute_score_MISclassGLMM(SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP etaSEXP, SEXP eta0SEXP, SEXP eta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP Nk_actualSEXP, SEXP YkiSEXP, SEXP XkiSEXP, SEXP Xki0SEXP, SEXP Xki1SEXP, SEXP WkSEXP, SEXP ZwkSEXP, SEXP Zwk0SEXP, SEXP Zwk1SEXP, SEXP XkSEXP, SEXP ZxkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP condOutSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP, SEXP len_betaSEXP, SEXP len_epsWSEXP, SEXP len_epsXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki(XkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki0(Xki0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki1(Xki1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk(ZwkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk0(Zwk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk1(Zwk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zxk(ZxkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< bool >::type condOut(condOutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    Rcpp::traits::input_parameter< int >::type len_beta(len_betaSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsW(len_epsWSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsX(len_epsXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_MISclassGLMM(sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_MISclassGLMM_slopes
NumericVector compute_score_MISclassGLMM_slopes(NumericVector sigma, NumericVector sigma0, NumericVector sigma1, NumericVector Delta, NumericVector Delta0, NumericVector Delta1, NumericVector eta, NumericVector eta0, NumericVector eta1, NumericVector etaW, NumericVector etaW0, NumericVector etaW1, NumericVector etaX, NumericVector rand_indic, NumericVector Nk_actual, NumericVector Yki, NumericMatrix Xki, NumericMatrix Xki0, NumericMatrix Xki1, NumericVector Wk, NumericMatrix Zwk, NumericMatrix Zwk0, NumericMatrix Zwk1, NumericVector Xk, NumericMatrix Zxk, NumericVector IDk, LogicalVector VALIDk, bool condOut, NumericVector GH_w, NumericVector GH_z, int len_beta, int len_epsW, int len_epsX);
RcppExport SEXP _MISclassICSpack_compute_score_MISclassGLMM_slopes(SEXP sigmaSEXP, SEXP sigma0SEXP, SEXP sigma1SEXP, SEXP DeltaSEXP, SEXP Delta0SEXP, SEXP Delta1SEXP, SEXP etaSEXP, SEXP eta0SEXP, SEXP eta1SEXP, SEXP etaWSEXP, SEXP etaW0SEXP, SEXP etaW1SEXP, SEXP etaXSEXP, SEXP rand_indicSEXP, SEXP Nk_actualSEXP, SEXP YkiSEXP, SEXP XkiSEXP, SEXP Xki0SEXP, SEXP Xki1SEXP, SEXP WkSEXP, SEXP ZwkSEXP, SEXP Zwk0SEXP, SEXP Zwk1SEXP, SEXP XkSEXP, SEXP ZxkSEXP, SEXP IDkSEXP, SEXP VALIDkSEXP, SEXP condOutSEXP, SEXP GH_wSEXP, SEXP GH_zSEXP, SEXP len_betaSEXP, SEXP len_epsWSEXP, SEXP len_epsXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta0(Delta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW(etaWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW0(etaW0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaW1(etaW1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type etaX(etaXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rand_indic(rand_indicSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nk_actual(Nk_actualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Yki(YkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki(XkiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki0(Xki0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xki1(Xki1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wk(WkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk(ZwkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk0(Zwk0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zwk1(Zwk1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xk(XkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zxk(ZxkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IDk(IDkSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type VALIDk(VALIDkSEXP);
    Rcpp::traits::input_parameter< bool >::type condOut(condOutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_w(GH_wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GH_z(GH_zSEXP);
    Rcpp::traits::input_parameter< int >::type len_beta(len_betaSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsW(len_epsWSEXP);
    Rcpp::traits::input_parameter< int >::type len_epsX(len_epsXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_MISclassGLMM_slopes(sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MISclassICSpack_compute_Omega", (DL_FUNC) &_MISclassICSpack_compute_Omega, 5},
    {"_MISclassICSpack_compute_Delta", (DL_FUNC) &_MISclassICSpack_compute_Delta, 4},
    {"_MISclassICSpack_compute_logLik_MISclassICS", (DL_FUNC) &_MISclassICSpack_compute_logLik_MISclassICS, 26},
    {"_MISclassICSpack_compute_score_MISclassICS", (DL_FUNC) &_MISclassICSpack_compute_score_MISclassICS, 48},
    {"_MISclassICSpack_compute_score_MISclassICS_slopes", (DL_FUNC) &_MISclassICSpack_compute_score_MISclassICS_slopes, 49},
    {"_MISclassICSpack_compute_logLik_MISclassGLMM", (DL_FUNC) &_MISclassICSpack_compute_logLik_MISclassGLMM, 18},
    {"_MISclassICSpack_compute_score_MISclassGLMM", (DL_FUNC) &_MISclassICSpack_compute_score_MISclassGLMM, 32},
    {"_MISclassICSpack_compute_score_MISclassGLMM_slopes", (DL_FUNC) &_MISclassICSpack_compute_score_MISclassGLMM_slopes, 33},
    {NULL, NULL, 0}
};

RcppExport void R_init_MISclassICSpack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
