# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Omega <- function(gamma, sigma, zeta, GH_w, GH_z) {
    .Call('_MISclassICSpack_compute_Omega', PACKAGE = 'MISclassICSpack', gamma, sigma, zeta, GH_w, GH_z)
}

compute_Delta <- function(sigma, eta, GH_w, GH_z) {
    .Call('_MISclassICSpack_compute_Delta', PACKAGE = 'MISclassICSpack', sigma, eta, GH_w, GH_z)
}

compute_logLik_MISclassICS <- function(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, minNk, GH_w, GH_z) {
    .Call('_MISclassICSpack_compute_logLik_MISclassICS', PACKAGE = 'MISclassICSpack', gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, minNk, GH_w, GH_z)
}

compute_score_MISclassICS <- function(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX) {
    .Call('_MISclassICSpack_compute_score_MISclassICS', PACKAGE = 'MISclassICSpack', gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX)
}

compute_score_MISclassICS_slopes <- function(gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX) {
    .Call('_MISclassICSpack_compute_score_MISclassICS_slopes', PACKAGE = 'MISclassICSpack', gamma, gamma0, gamma1, sigma, sigma0, sigma1, Omega, Omega0, Omega1, Delta, Delta0, Delta1, zeta, zeta0, zeta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk, Nk_actual, Zk, Zk0, Zk1, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, minNk, condSize, condOut, GH_w, GH_z, len_alpha, len_beta, len_epsW, len_epsX)
}

compute_logLik_MISclassGLMM <- function(sigma, sigma0, sigma1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, GH_w, GH_z) {
    .Call('_MISclassICSpack_compute_logLik_MISclassGLMM', PACKAGE = 'MISclassICSpack', sigma, sigma0, sigma1, Delta, Delta0, Delta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Wk, Xk, IDk, VALIDk, GH_w, GH_z)
}

compute_score_MISclassGLMM <- function(sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX) {
    .Call('_MISclassICSpack_compute_score_MISclassGLMM', PACKAGE = 'MISclassICSpack', sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX)
}

compute_score_MISclassGLMM_slopes <- function(sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX) {
    .Call('_MISclassICSpack_compute_score_MISclassGLMM_slopes', PACKAGE = 'MISclassICSpack', sigma, sigma0, sigma1, Delta, Delta0, Delta1, eta, eta0, eta1, etaW, etaW0, etaW1, etaX, rand_indic, Nk_actual, Yki, Xki, Xki0, Xki1, Wk, Zwk, Zwk0, Zwk1, Xk, Zxk, IDk, VALIDk, condOut, GH_w, GH_z, len_beta, len_epsW, len_epsX)
}

